cc_binary(
    name = "apanalysis",
    srcs = ["apanalysis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)

cc_binary(
    name = "f0analysis",
    srcs = ["f0analysis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)

cc_binary(
    name = "readandsynthesis",
    srcs = ["readandsynthesis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)

cc_binary(
    name = "spanalysis",
    srcs = ["spanalysis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)

