cc_binary(
    name = "analysis",
    srcs = ["analysis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)

cc_binary(
    name = "synthesis",
    srcs = ["synthesis.cpp"],
    deps = [
      "//src:libworld",
      "//tools:libtools",
    ],
    copts = [
      "-Isrc",
      "-Itools",
    ],
)
