package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libworld",
    srcs = glob(
        ["*.cc"],
    ),
    hdrs = glob([
        "world/*.h",
    ]),
    copts = ["-Isrc"],
)
